steps:
- id: 'tag'
  name: 'bridgecrew/yor'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
 
        yor tag -d . --config-file tag-custom.yaml 
    
        yor tag -d . --output cli --output-json-file hasil.json

        git config --global user.email "leosaragih001@gmail.com"

        git config --global user.name "saktil"

        git add .

        git commit -m "commit coba"

        git push --set-upstream origin master

        
      
     
      
