steps:
- id: 'tag'
  name: 'bridgecrew/yor'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
 
        yor tag -d . --config-file tag-custom.yaml 
    
        yor tag -d . --output cli --output-json-file hasil.json

        git add .

        git commit -m "commit coba"

        gp 

        
      
     
      
